#To clear everything about docker
#docker system prune -a --volumes

#to refrsh requirements.txt
#pip3 freeze > requirements.txt

FROM python:3.9-alpine

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /app
WORKDIR /app
COPY . /app

# Install postgres client
RUN apk add --update --no-cache postgresql-client

# Install individual dependencies
# so that we could avoid install extra packages
RUN apk add --update --no-cache --virtual .tmp-build-deps \
	gcc libc-dev linux-headers postgresql-dev
RUN pip install -r ./requirements.txt

# Remove dependencies
RUN apk del .tmp-build-deps

# copy entrypoint.sh
COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

COPY ./scripts/db/init.sql /docker-entrypoint-initdb.d

# [Security] Limit the scope of user who run the docker image
RUN adduser -D user

USER user

