version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    command: "./entrypoint.sh"
    depends_on:
      - db
  db:
    image: postgres
    command: "postgres -c stats_temp_directory=/tmp"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - ./.env
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
      - ./data/db:/var/lib/postgresql/data

