# Generated by Django 4.0.2 on 2022-02-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('number', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('seats_count', models.IntegerField()),
            ],
        ),
    ]
